# GitHub Actions Main Configuration File
name: Build

on:
  pull_request:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        
      - name: Setup MSBuild Path
        uses: warrenbuckley/Setup-MSBuild@v1
        
      - name: Setup VSTest Path
        uses: darenm/Setup-VSTest@v1
       
      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.0.2
        
      - name: Restore Build Cache
        id: LeetCode-package-cache
        uses: actions/cache@v2
        with:
          path: ./packages
          key: ${{ runner.os }}-LeetCode-package-cache-${{ hashFiles('LeetCode/package.json') }}
     
      - name: Restore NuGet Packages
        if: steps.LeetCode-package-cache.outputs.cache-hit != 'true'
        run: nuget restore Coding-Practice-CSharp.sln
 
      - name: Build and Publish
        run: msbuild Coding-Practice-CSharp.sln /p:Configuration=Release /p:DeployOnBuild=true /p:PublishProfile=FolderProfile 
        
      - name: Run Tests
        run: vstest.console.exe LeetCode\bin\Release\CodingPractice.dll /Parallel
